Algoritmo "ParOuImparProcedimento"

Var

N : inteiro

Procedimento ParOuImpar (V: inteiro)

Inicio

 Escreval(" O valor de V é : ", V)
 Escreval(" O valor de N é : ", N)
  Se (V %2 = 0) entao
     Escreval("O numero ", V, " é PAR")
  senao
       Escreval(" O numero ", V, " é IMPAR")
  fimse
Fimprocedimento

Inicio

Escreva("Digite um numero: ")
Leia (N)
ParOuImpar(N)



Fimalgoritmo